### ISSUE TITLE
running error..

### ISSUE THREAD

**Issue by SlZeroth** [mit-han-lab/fastcomposer#22]
(ip-adapter) PS C:\Users\qkrwn\ML\fastcomposer> python demo/run_gradio.py --finetuned_model_path model/fastcomposer/pytorch_model.bin  --mixed_precision "fp16"
>>
Traceback (most recent call last):
  File "C:\Users\qkrwn\ML\fastcomposer\demo\run_gradio.py", line 4, in <module>
    from demo.pipeline import convert_model_to_pipeline
ModuleNotFoundError: No module named 'demo'
(ip-adapter) PS C:\Users\qkrwn\ML\fastcomposer>

I got "No module named 'demo' errror
how can I solve this issue?

**Comment by SlZeroth** [comment]
thank you for your answer!  I solved with add __init__.py in the demo folder 
but I got second issue

  File "C:\Users\qkrwn\ML\fastcomposer\demo\run_gradio.py", line 4, in <module>
    from demo.pipeline import convert_model_to_pipeline
  File "C:\Users\qkrwn\anaconda3\envs\ip-adapter\lib\site-packages\fastcomposer-0.0.1-py3.10.egg\demo\pipeline.py", line 1, in <module>
    from fastcomposer.pipeline import StableDiffusionFastCompposerPipeline
  File "C:\Users\qkrwn\anaconda3\envs\ip-adapter\lib\site-packages\fastcomposer-0.0.1-py3.10.egg\fastcomposer\pipeline.py", line 1, in <module>
    from fastcomposer.pipeline import StableDiffusionFastCompposerPipeline
  File "C:\Users\qkrwn\anaconda3\envs\ip-adapter\lib\site-packages\fastcomposer-0.0.1-py3.10.egg\fastcomposer\model.py", line 191, in <module>
  File "C:\Users\qkrwn\anaconda3\envs\ip-adapter\lib\site-packages\fastcomposer-0.0.1-py3.10.egg\fastcomposer\model.py", line 192, in FastComposerTextEncoder
AttributeError: type object 'CLIPTextTransformer' has no attribute '_build_causal_attention_mask'

**Comment by SlZeroth** [comment]
thank you I solved !
